// 第 5 章:串列與元組
export const CH5 = {
  num: 5,
  emoji: "📦",
  title: "串列星系",
  subtitle: "串列宣告與存取、迴圈讀取、搜尋、增刪、排序、元組",
  levels: [
    {
      id: "c5-create",
      planet: "📦",
      title: "貨艙開箱",
      topic: "串列宣告與存取",
      story: "串列(List)是一排收納格,用索引取物——注意索引從 0 開始,-1 是最後一格!",
      instructions: [
        "建立 <code>scores = [80, 95, 70]</code>",
        "印出第一個元素 <code>scores[0]</code>",
        "印出最後一個元素 <code>scores[-1]</code>",
      ],
      starter: "# 建立 scores 串列並取出頭尾\n",
      hint: "scores[0] 是 80,scores[-1] 是 70(-1 代表倒數第一個)。",
      xp: 40,
      tests: [
        { name: "scores 正確", code: 'assert ns.get("scores") == [80, 95, 70], "scores 要是 [80, 95, 70]"' },
        { name: "印出頭尾", code: 'assert "80" in output and "70" in output, "要印出 scores[0] 和 scores[-1]"' },
      ],
    },
    {
      id: "c5-forin",
      planet: "👥",
      title: "隊員點名",
      topic: "for…in 讀取串列",
      story: "出發前要點名!用 for 迴圈把每位隊員逐一叫出來。",
      instructions: [
        "已有隊員串列 <code>crew</code>",
        "用 <code>for</code> 迴圈搭配 f-string,每行印出 <code>隊員:名字</code>",
      ],
      starter: 'crew = ["艾達", "小圖", "波波"]\n\n# for 變數 in 串列\n',
      hint: 'for member in crew: 底下 print(f"隊員:{member}")。',
      xp: 40,
      tests: [
        { name: "有使用 for…in", code: 'assert "for" in src and " in " in src, "要用 for…in 讀取串列"' },
        { name: "點名完整", code: 'assert [l.strip() for l in output.strip().splitlines()] == ["隊員:艾達", "隊員:小圖", "隊員:波波"], "三位隊員都要以 隊員:名字 格式印出"' },
      ],
    },
    {
      id: "c5-search",
      planet: "🔎",
      title: "搜尋與計次",
      topic: "index() 與 count()",
      story: "在訊號紀錄裡找出目標的位置,並統計某個數值出現幾次。",
      instructions: [
        "已有 <code>nums = [5, 3, 8, 3, 3]</code>",
        "建立 <code>idx = nums.index(8)</code>(8 的位置)",
        "建立 <code>cnt = nums.count(3)</code>(3 出現幾次)",
        "印出兩個結果",
      ],
      starter: "nums = [5, 3, 8, 3, 3]\n\n# 完成 idx 和 cnt 並印出\n",
      hint: "index() 回傳第一次出現的索引;count() 回傳出現次數。",
      xp: 40,
      tests: [
        { name: "idx == 2", code: 'assert ns.get("idx") == 2, "8 在索引 2 的位置(從 0 算起)"' },
        { name: "cnt == 3", code: 'assert ns.get("cnt") == 3, "3 出現了 3 次"' },
      ],
    },
    {
      id: "c5-append",
      planet: "📥",
      title: "裝貨作業",
      topic: "append() 與 insert()",
      story: "append 把貨物放到最後面,insert 可以插隊放到指定位置。",
      instructions: [
        "已有 <code>todo = [\"檢查引擎\"]</code>",
        "用 <code>append()</code> 加入 <code>\"補充燃料\"</code>",
        "用 <code>insert(0, ...)</code> 把 <code>\"穿太空衣\"</code> 插到最前面",
        "印出最後的 todo",
      ],
      starter: 'todo = ["檢查引擎"]\n\n# append 和 insert\n',
      hint: 'todo.append("補充燃料") 加到尾端;todo.insert(0, "穿太空衣") 插到索引 0。',
      xp: 40,
      tests: [
        { name: "有使用 append 和 insert", code: 'assert ".append(" in src and ".insert(" in src, "兩個方法都要用到"' },
        { name: "順序正確", code: 'assert ns.get("todo") == ["穿太空衣", "檢查引擎", "補充燃料"], "最後順序:穿太空衣、檢查引擎、補充燃料"' },
      ],
    },
    {
      id: "c5-remove",
      planet: "🗑️",
      title: "卸貨作業",
      topic: "remove() 與 pop()",
      story: "remove 依「值」刪除第一個符合的項目;pop 依「位置」取出項目(預設最後一個)。",
      instructions: [
        "已有 <code>items = [\"地圖\", \"故障零件\", \"羅盤\", \"故障零件\"]</code>",
        "用 <code>remove()</code> 刪除第一個 <code>\"故障零件\"</code>",
        "用 <code>last = items.pop()</code> 取出最後一項",
        "印出 items 和 last",
      ],
      starter: 'items = ["地圖", "故障零件", "羅盤", "故障零件"]\n\n# remove 和 pop\n',
      hint: 'items.remove("故障零件") 只刪第一個;items.pop() 取出並回傳最後一項。',
      xp: 50,
      tests: [
        { name: "items 剩下正確項目", code: 'assert ns.get("items") == ["地圖", "羅盤"], "刪掉一個故障零件、pop 掉另一個後,應剩 [地圖, 羅盤]"' },
        { name: "last 是故障零件", code: 'assert ns.get("last") == "故障零件", "pop() 取出的最後一項是 故障零件"' },
      ],
    },
    {
      id: "c5-sort",
      planet: "📶",
      title: "排序天線陣",
      topic: "sort() 與 reverse()",
      story: "sort() 由小到大排;接著 reverse() 反轉,就變成由大到小!",
      instructions: [
        "已有 <code>scores = [75, 92, 60, 88]</code>",
        "先 <code>sort()</code> 再 <code>reverse()</code>,讓 scores 變成由大到小",
        "印出 scores",
      ],
      starter: "scores = [75, 92, 60, 88]\n\n# sort 之後 reverse\n",
      hint: "scores.sort() → [60,75,88,92];scores.reverse() → [92,88,75,60]。這兩個方法會直接改變原串列。",
      xp: 50,
      tests: [
        { name: "有使用 sort 和 reverse", code: 'assert ".sort(" in src and ".reverse(" in src, "要用 sort() 和 reverse() 兩個方法"' },
        { name: "由大到小", code: 'assert ns.get("scores") == [92, 88, 75, 60], "最後應該是 [92, 88, 75, 60]"' },
      ],
    },
    {
      id: "c5-sorted",
      planet: "🧬",
      title: "sorted 複製排序",
      topic: "sorted() 函式",
      story: "sort() 會改變原本的串列,sorted() 則是產生排好的新串列、原本的完好如初。",
      instructions: [
        "已有 <code>data = [9, 1, 7]</code>",
        "建立 <code>ranked = sorted(data)</code>",
        "印出 data 和 ranked,確認原串列沒變",
      ],
      starter: "data = [9, 1, 7]\n\n# 用 sorted() 產生新串列\n",
      hint: "ranked = sorted(data) — 注意是 sorted(data) 而不是 data.sort()。",
      xp: 50,
      tests: [
        { name: "有使用 sorted()", code: 'assert "sorted(" in src, "要用 sorted() 函式"' },
        { name: "ranked 排好了", code: 'assert ns.get("ranked") == [1, 7, 9], "ranked 應該是 [1, 7, 9]"' },
        { name: "data 保持原樣", code: 'assert ns.get("data") == [9, 1, 7], "sorted() 不會改變原串列,data 應該還是 [9, 1, 7]"' },
      ],
    },
    {
      id: "c5-tuple",
      planet: "🔒",
      title: "元組保險箱",
      topic: "元組 Tuple",
      story: "元組像上了鎖的串列——內容不能改。想修改?先轉成串列,改完再轉回來。",
      instructions: [
        "建立元組 <code>point = (3, 4)</code>",
        "轉成串列 <code>lst = list(point)</code>,用 append 加入 <code>5</code>",
        "轉回元組 <code>tp = tuple(lst)</code>,印出 tp",
      ],
      starter: "# 元組 → 串列 → 修改 → 元組\n",
      hint: "point = (3, 4) 用小括號;list() 和 tuple() 可以互相轉換。",
      xp: 50,
      tests: [
        { name: "point 是元組", code: 'assert ns.get("point") == (3, 4) and isinstance(ns.get("point"), tuple), "point 要是元組 (3, 4)"' },
        { name: "tp 轉換正確", code: 'assert ns.get("tp") == (3, 4, 5) and isinstance(ns.get("tp"), tuple), "tp 應該是元組 (3, 4, 5)"' },
      ],
    },
  ],
};
