// 第 6 章:字典
export const CH6 = {
  num: 6,
  emoji: "🗂️",
  title: "字典星系",
  subtitle: "鍵值對、字典維護、in、keys/values、items、setdefault",
  levels: [
    {
      id: "c6-create",
      planet: "🗂️",
      title: "建立檔案卡",
      topic: "建立字典與取值",
      story: "字典用「鍵-值」對儲存資料,像幫每筆資料貼上標籤,用標籤就能取值。",
      instructions: [
        "建立字典 <code>profile = {\"name\": \"小艾\", \"hp\": 100}</code>",
        "用 <code>profile[\"name\"]</code> 印出名字",
      ],
      starter: "# 建立 profile 字典並取值\n",
      hint: '字典用大括號:{"鍵": 值}。取值用 profile["name"]。',
      xp: 40,
      tests: [
        { name: "profile 正確", code: 'assert ns.get("profile") == {"name": "小艾", "hp": 100}, "profile 要有 name 和 hp 兩個鍵"' },
        { name: "印出名字", code: 'assert "小艾" in output, "記得 print(profile[\\"name\\"])"' },
      ],
    },
    {
      id: "c6-maintain",
      planet: "🔧",
      title: "字典維護站",
      topic: "字典維護(改、增、刪)",
      story: "衛星資料庫要大更新:改資料、加資料、刪資料,一次搞定!",
      instructions: [
        "已有 <code>moons = {\"地球\": 1, \"火星\": 0}</code>",
        "把 <code>\"火星\"</code> 的值改成 <code>2</code>",
        "新增 <code>\"木星\"</code>,值是 <code>95</code>",
        "用 <code>del</code> 刪除 <code>\"地球\"</code>,印出 moons",
      ],
      starter: 'moons = {"地球": 1, "火星": 0}\n\n# 改、增、刪\n',
      hint: 'moons["火星"] = 2 改值;moons["木星"] = 95 新增;del moons["地球"] 刪除。',
      xp: 40,
      tests: [
        { name: "有使用 del", code: 'assert "del" in src, "要用 del 刪除鍵"' },
        { name: "最終內容正確", code: 'assert ns.get("moons") == {"火星": 2, "木星": 95}, "最後應該只剩 火星:2 和 木星:95"' },
      ],
    },
    {
      id: "c6-in",
      planet: "❓",
      title: "in 查驗官",
      topic: "in 功能",
      story: "查資料前先確認「這個鍵存在嗎?」,直接取不存在的鍵會爆出 KeyError!",
      instructions: [
        "已有 <code>moons = {\"地球\": 1, \"木星\": 95}</code>",
        "建立 <code>r1 = \"地球\" in moons</code>",
        "建立 <code>r2 = \"冥王星\" in moons</code>",
        "印出兩個結果",
      ],
      starter: 'moons = {"地球": 1, "木星": 95}\n\n# 用 in 檢查鍵是否存在\n',
      hint: '"鍵" in 字典 會回傳 True 或 False。',
      xp: 40,
      tests: [
        { name: "r1 是 True", code: 'assert ns.get("r1") is True, "地球在字典裡,r1 應該是 True"' },
        { name: "r2 是 False", code: 'assert ns.get("r2") is False, "冥王星不在字典裡,r2 應該是 False"' },
      ],
    },
    {
      id: "c6-keysvalues",
      planet: "🔑",
      title: "鑰匙與寶物",
      topic: "keys 及 values 方法",
      story: "keys() 拿出所有標籤,values() 拿出所有內容物,盤點資料庫全靠它們。",
      instructions: [
        "已有 <code>moons = {\"地球\": 1, \"火星\": 2, \"木星\": 95}</code>",
        "建立 <code>ks = list(moons.keys())</code>",
        "建立 <code>vs = list(moons.values())</code>",
        "印出兩個串列",
      ],
      starter: 'moons = {"地球": 1, "火星": 2, "木星": 95}\n\n# 取出所有鍵和所有值\n',
      hint: "moons.keys() 和 moons.values() 外面包 list() 轉成串列。",
      xp: 40,
      tests: [
        { name: "ks 正確", code: 'assert ns.get("ks") == ["地球", "火星", "木星"], "ks 應該是所有的鍵"' },
        { name: "vs 正確", code: 'assert ns.get("vs") == [1, 2, 95], "vs 應該是所有的值"' },
      ],
    },
    {
      id: "c6-items",
      planet: "📋",
      title: "items 巡覽車",
      topic: "items 方法",
      story: "items() 讓你一次拿到「鍵和值」,搭配 for 迴圈巡覽整個字典。",
      instructions: [
        "已有 <code>moons</code> 字典",
        "用 <code>for k, v in moons.items():</code> 迴圈",
        "每行印出 <code>鍵 有 值 顆衛星</code>(例如:地球 有 1 顆衛星)",
      ],
      starter: 'moons = {"地球": 1, "火星": 2, "木星": 95}\n\n# 用 items() 巡覽\n',
      hint: 'for k, v in moons.items(): 底下 print(f"{k} 有 {v} 顆衛星")。',
      xp: 50,
      tests: [
        { name: "有使用 items()", code: 'assert ".items()" in src, "要用 items() 方法"' },
        { name: "輸出完整", code: 'assert "地球 有 1 顆衛星" in output and "火星 有 2 顆衛星" in output and "木星 有 95 顆衛星" in output, "三顆星球都要印出 鍵 有 值 顆衛星"' },
      ],
    },
    {
      id: "c6-setdefault",
      planet: "🥇",
      title: "setdefault 獎牌榜",
      topic: "setdefault 方法",
      story: "setdefault:鍵存在就回傳原值;不存在就先設定預設值再回傳。獎牌榜統計神器!",
      instructions: [
        "已有 <code>medals = {\"金牌\": 3}</code>",
        "建立 <code>g = medals.setdefault(\"金牌\", 0)</code>(已存在 → 拿到 3)",
        "建立 <code>s = medals.setdefault(\"銀牌\", 5)</code>(不存在 → 設成 5)",
        "印出 g、s 和 medals",
      ],
      starter: 'medals = {"金牌": 3}\n\n# setdefault 兩連發\n',
      hint: "setdefault(鍵, 預設值):金牌已存在所以回傳 3 且不變;銀牌不存在所以新增為 5。",
      xp: 50,
      tests: [
        { name: "有使用 setdefault", code: 'assert "setdefault" in src, "要用 setdefault 方法"' },
        { name: "g == 3(原值不變)", code: 'assert ns.get("g") == 3, "金牌已存在,setdefault 回傳原本的 3"' },
        { name: "s == 5(新增預設)", code: 'assert ns.get("s") == 5 and ns.get("medals") == {"金牌": 3, "銀牌": 5}, "銀牌不存在,應新增為 5"' },
      ],
    },
  ],
};
