// 第 7 章:函式與模組
export const CH7 = {
  num: 7,
  emoji: "🛠️",
  title: "函式星系",
  subtitle: "自訂函式、預設參數、變數範圍、數值/字串函式、random 模組",
  levels: [
    {
      id: "c7-def",
      planet: "🛠️",
      title: "打造函式",
      topic: "自訂函式",
      story: "把常用的計算包成函式,任何船艦都能重複呼叫,不用每次重寫!",
      instructions: [
        "寫函式 <code>area(w, h)</code>,回傳 <code>w * h</code>",
        "呼叫 <code>area(3, 4)</code> 並印出結果",
      ],
      starter: "# def 函式名稱(參數):\n#     return 結果\n",
      hint: "def area(w, h): 換行縮排 return w * h。",
      xp: 50,
      tests: [
        { name: "area(3, 4) == 12", code: 'assert ns["area"](3, 4) == 12, "area(3, 4) 應該回傳 12"' },
        { name: "area(5, 5) == 25", code: 'assert ns["area"](5, 5) == 25, "area(5, 5) 應該回傳 25"' },
        { name: "有印出結果", code: 'assert "12" in output, "記得印出 area(3, 4) 的結果"' },
      ],
    },
    {
      id: "c7-default",
      planet: "🎖️",
      title: "預設參數禮儀官",
      topic: "參數預設值",
      story: "打招呼系統:沒指定頭銜就用預設的「船長」,有指定就用指定的。",
      instructions: [
        "寫函式 <code>greet(name, title=\"船長\")</code>",
        "回傳 <code>f\"{title}{name}你好\"</code>",
        "分別印出 <code>greet(\"小艾\")</code> 和 <code>greet(\"小圖\", \"技師\")</code>",
      ],
      starter: "# 第二個參數要有預設值\n",
      hint: 'def greet(name, title="船長"): 參數寫 = 就是預設值,呼叫時可給可不給。',
      xp: 50,
      tests: [
        { name: "用預設頭銜", code: 'assert ns["greet"]("小艾") == "船長小艾你好", "greet(\\"小艾\\") 應該用預設頭銜:船長小艾你好"' },
        { name: "用指定頭銜", code: 'assert ns["greet"]("小圖", "技師") == "技師小圖你好", "greet(\\"小圖\\", \\"技師\\") 應該是:技師小圖你好"' },
      ],
    },
    {
      id: "c7-scope",
      planet: "🧯",
      title: "變數範圍除錯",
      topic: "變數有效範圍",
      story: "函式裡的變數是「區域變數」,改不到外面的!正確做法是用 return 把結果傳出來。",
      instructions: [
        "已有 <code>fuel = 50</code>",
        "寫函式 <code>add_fuel(f, amount)</code>,回傳 <code>f + amount</code>",
        "用 <code>fuel = add_fuel(fuel, 10)</code> 更新燃料",
        "印出 fuel(應該是 60)",
      ],
      starter: "fuel = 50\n\n# 用 return 的方式安全加燃料\n",
      hint: "函式內算好結果 return 出來,外面用 fuel = add_fuel(fuel, 10) 接住新值。",
      xp: 50,
      tests: [
        { name: "有使用 return", code: 'assert "return" in src, "函式要用 return 回傳結果"' },
        { name: "fuel 更新為 60", code: 'assert ns.get("fuel") == 60, "fuel 最後應該是 50 + 10 = 60"' },
        { name: "有印出", code: 'assert "60" in output, "記得 print(fuel)"' },
      ],
    },
    {
      id: "c7-numfunc",
      planet: "📊",
      title: "數值函式儀表板",
      topic: "數值函式(max/min/sum/round)",
      story: "艦隊成績分析:最高分、最低分、總分、平均,內建函式一把罩。",
      instructions: [
        "已有 <code>data = [68, 92, 45, 77]</code>",
        "建立 <code>highest = max(data)</code>、<code>lowest = min(data)</code>",
        "建立 <code>total = sum(data)</code>",
        "建立 <code>avg = round(total / len(data), 1)</code>,全部印出",
      ],
      starter: "data = [68, 92, 45, 77]\n\n# max、min、sum、round\n",
      hint: "round(數值, 1) 四捨五入到小數第 1 位;len(data) 是資料筆數。",
      xp: 50,
      tests: [
        { name: "highest == 92", code: 'assert ns.get("highest") == 92, "最高分是 92"' },
        { name: "lowest == 45", code: 'assert ns.get("lowest") == 45, "最低分是 45"' },
        { name: "total == 282", code: 'assert ns.get("total") == 282, "總分是 282"' },
        { name: "avg == 70.5", code: 'assert ns.get("avg") == 70.5, "平均 282/4 = 70.5"' },
      ],
    },
    {
      id: "c7-split",
      planet: "✂️",
      title: "字串裁縫室",
      topic: "連接及分割字串",
      story: "split 把一條字串剪成串列,join 再把串列縫回一條字串。",
      instructions: [
        "已有 <code>s = \"太陽,月亮,星星\"</code>",
        "建立 <code>parts = s.split(\",\")</code>",
        "建立 <code>joined = \"-\".join(parts)</code>",
        "印出 parts 和 joined",
      ],
      starter: 's = "太陽,月亮,星星"\n\n# split 再 join\n',
      hint: 's.split(",") 以逗號切開;"-".join(parts) 用連字號接回去。',
      xp: 50,
      tests: [
        { name: "parts 切割正確", code: 'assert ns.get("parts") == ["太陽", "月亮", "星星"], "parts 應該是三個詞的串列"' },
        { name: "joined 連接正確", code: 'assert ns.get("joined") == "太陽-月亮-星星", "joined 應該用 - 連接"' },
      ],
    },
    {
      id: "c7-replace",
      planet: "🔁",
      title: "搜尋取代工坊",
      topic: "搜尋及取代字串",
      story: "find 回報文字第一次出現的位置(找不到回 -1),replace 把指定文字全部換掉。",
      instructions: [
        "已有 <code>msg = \"Python 好好玩\"</code>",
        "建立 <code>pos = msg.find(\"好\")</code>",
        "建立 <code>new_msg = msg.replace(\"好\", \"超\")</code>",
        "印出 pos 和 new_msg",
      ],
      starter: 'msg = "Python 好好玩"\n\n# find 和 replace\n',
      hint: "find 從 0 開始數(空格也算一格);replace(舊, 新) 會換掉所有符合的字。",
      xp: 50,
      tests: [
        { name: "pos == 7", code: 'assert ns.get("pos") == 7, "第一個 好 在索引 7(P=0 開始數,空格也算)"' },
        { name: "取代正確", code: 'assert ns.get("new_msg") == "Python 超超玩", "replace 會把兩個 好 都換成 超"' },
      ],
    },
    {
      id: "c7-random",
      planet: "🎲",
      title: "亂數骰子塔",
      topic: "random 模組",
      story: "要用外部模組得先 import!random.randint(1, 6) 就像擲一顆六面骰。",
      instructions: [
        "<code>import random</code>",
        "寫函式 <code>roll()</code>,回傳 <code>random.randint(1, 6)</code>",
        "呼叫幾次 roll() 並印出,感受亂數的變化",
      ],
      starter: "# 先 import random\n",
      hint: "import random 寫在最上面;random.randint(1, 6) 會回傳 1~6 的隨機整數。",
      xp: 60,
      tests: [
        { name: "有 import random", code: 'assert "import random" in src, "要先 import random 才能用亂數"' },
        { name: "骰子範圍正確", code: 'results = [ns["roll"]() for _ in range(60)]\nassert all(1 <= r <= 6 for r in results), "roll() 應該永遠回傳 1~6"' },
        { name: "真的是亂數", code: 'results = [ns["roll"]() for _ in range(60)]\nassert len(set(results)) > 1, "擲 60 次應該會出現不同點數,檢查是不是寫死了"' },
      ],
    },
  ],
};
